### ISSUE TITLE
"[Voice Changer] Voice Changer is not selected." and "Cannot read properties of null"

### ISSUE THREAD

**Issue by Cragsand** [w-okada/voice-changer#301]
### Issue Type

Bug Report

### vc client version number

1.5.3.4d

### OS

Windows 10 (Swedish)

### GPU

RTX2080Ti

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

When loading the sample model pth and index file I get an error message and the "Switch Model" dropdown box doesn't fill. The intended behavior according to the demo video it should fill out after uploading the model.

Could be a UI bug because I use Swedish Windows 10? 

Screenshot:
![bild](https://github.com/w-okada/voice-changer/assets/49168045/81b10829-4c3b-41ac-86fb-ed65a78b872a)

Log:
```
N:\Python\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     -
-content_vec_500_onnx pretrain/checkpoint_best_legacy_500.onnx     --content_vec_500_onnx_on false     --hubert_base pretrain/hubert_base.p
t     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrai
n/nsf_hifigan/model     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    Voice Changerを起動しています。
++    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
VoiceChanger Initialized (GPU_NUM:1, mps_enabled:False)
 [INFO] [DSH]  voice-changer-native-client.exe
 [INFO] [DSH]  Creating WndMsg Listener Window
 [INFO] [DSH]  Get number of capabilities
 [INFO] [DSH]  Get stream caps: 0
 [INFO] [DSH]  Get stream caps: 1
 [INFO] [DSH]  Get stream caps: 2
 [INFO] [DSH]  Get stream caps: 3
 [INFO] [DSH]  Get stream caps: 4
 [INFO] [DSH]  Get stream caps: 5
 [INFO] [DSH]  Get stream caps: 6
 [INFO] [DSH]  Get stream caps: 7
 [INFO] [DSH]  Get stream caps: 8
 [INFO] [DSH]  Get stream caps: 9
 [INFO] [DSH]  Get stream caps: 10
 [INFO] [DSH]  Get stream caps: 11
 [INFO] [DSH]  Get stream caps: 12
 [INFO] [DSH]  Get stream caps: 13
 [INFO] [DSH]  Get stream caps: 14
 [INFO] [DSH]  Get stream caps: 15
 [INFO] [DSH]  Get stream caps: 16
 [INFO] [DSH]  Get stream caps: 17
 [INFO] [DSH]  Get stream caps: 18
 [INFO] [DSH]  Get stream caps: 19
 [INFO] [DSH]  Get stream caps: 20
 [INFO] [DSH]  Get stream caps: 21
 [INFO] [DSH]  Get stream caps: 22
 [INFO] [DSH]  Get stream caps: 23
 [INFO] [DSH]  Get stream caps: 24
 [INFO] [DSH]  Get stream caps: 25
 [INFO] [DSH]  Get stream caps: 26
 [INFO] [DSH]  Get stream caps: 27
 [INFO] [DSH]  Get stream caps: 28
 [INFO] [DSH]  Get stream caps: 29
 [INFO] [DSH]  Get stream caps: 30
 [INFO] [DSH]  Get stream caps: 31
 [INFO] [DSH]  Get stream caps: 32
 [INFO] [DSH]  Destroying object
 [INFO] [DSH]  Destroying WndMsg Listener Window
 [INFO] [DSH]  Destroyed window
 [INFO] [DSH]  Unregistered window class
[2023-06-07 20:18:43] connet sid : akQ0-qEjO0q_B-ePAAAB
[2023-06-07 20:18:43] connet sid : qa8aDP4mzE3FLi3eAAAD
2023-06-07 20:18:44 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-06-07 20:18:44 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-06-07 20:18:44 | INFO | faiss.loader | Loading faiss.
2023-06-07 20:18:44 | INFO | faiss.loader | Successfully loaded faiss.
[Voice Changer] RVC initialization:  VoiceChangerParams(model_dir='model_dir', content_vec_500='pretrain/checkpoint_best_legacy_500.pt', co
ntent_vec_500_onnx='pretrain/checkpoint_best_legacy_500.onnx', content_vec_500_onnx_on=0, hubert_base='pretrain/hubert_base.pt', hubert_bas
e_jp='pretrain/rinna_hubert_base_jp.pt', hubert_soft='pretrain/hubert/hubert-soft-0d54a1f4.pt', nsf_hifigan='pretrain/nsf_hifigan/model', r
vc_sample_mode='production')
[Voice Changer] loading sample info error: RVCModelSample.__init__() got an unexpected keyword argument 'icon'
[Voice Changer] Prepare Model of slot: 0
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer]  exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 25, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 45, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 12, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] Loading index...
Try loading... model_dir\rvc\0\DendenMei.index
local variable 'embedder' referenced before assignment
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 312, in switchModelType
  File "voice_changer\RVC\RVC.py", line 92, in __init__
  File "voice_changer\RVC\RVC.py", line 244, in prepareModel
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 45, in createPipeline
UnboundLocalError: local variable 'embedder' referenced before assignment

Exception ignored in: <function RVC.__del__ at 0x00000243210217E0>
Traceback (most recent call last):
  File "voice_changer\RVC\RVC.py", line 401, in __del__
AttributeError: pipeline
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 331, in loadModel
Exceptions.VoiceChangerIsNotSelectedException: 'Voice Changer is not selected.'

[Voice Changer] Model Load Error! Check your model is valid. 'Voice Changer is not selected.'
[12920:0607/202040.259:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
[Voice Changer] Voice Changer is not selected.
[2023-06-07 20:21:54] connet sid : 1CjpRhN8bDn34Fi7AAAF
[2023-06-07 20:21:54] connet sid : 1sVM1QKkgyNBqMshAAAH
[Voice Changer] RVC initialization:  VoiceChangerParams(model_dir='model_dir', content_vec_500='pretrain/checkpoint_best_legacy_500.pt', co
ntent_vec_500_onnx='pretrain/checkpoint_best_legacy_500.onnx', content_vec_500_onnx_on=0, hubert_base='pretrain/hubert_base.pt', hubert_bas
e_jp='pretrain/rinna_hubert_base_jp.pt', hubert_soft='pretrain/hubert/hubert-soft-0d54a1f4.pt', nsf_hifigan='pretrain/nsf_hifigan/model', r
vc_sample_mode='production')
[Voice Changer] loading sample info error: RVCModelSample.__init__() got an unexpected keyword argument 'icon'
[Voice Changer] Prepare Model of slot: 0
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer]  exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 25, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 45, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 12, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] Loading index...
Try loading... model_dir\rvc\0\DendenMei.index
local variable 'embedder' referenced before assignment
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 312, in switchModelType
  File "voice_changer\RVC\RVC.py", line 92, in __init__
  File "voice_changer\RVC\RVC.py", line 244, in prepareModel
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 45, in createPipeline
UnboundLocalError: local variable 'embedder' referenced before assignment

Exception ignored in: <function RVC.__del__ at 0x00000243210217E0>
Traceback (most recent call last):
  File "voice_changer\RVC\RVC.py", line 401, in __del__
AttributeError: pipeline
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
```
Clicking "Update defaults" then results in a crash

![bild](https://github.com/w-okada/voice-changer/assets/49168045/0240c8c1-f96d-4b45-9441-e077f7e36ab4)

![bild](https://github.com/w-okada/voice-changer/assets/49168045/70e82b20-aa4a-4a95-b678-8a6e3d6698c9)

Is there some setting file I can manually edit somewhere and fill in the selection box manually?
I can't find where any such setting file would be in the documentations. 
Hitting "Clear setting" in the UI doesn't make any difference.

Apologies if this is a stupid question and I'm missing something really obvious.

**Comment by w-okada** [comment]
What is ”DendenMei.index”?

Given that this file exists, I can assume that you've run this software several times. What were you doing when you experienced this issue?

**Comment by Cragsand** [comment]
> What is ”DendenMei.index”?
> 
> Given that this file exists, I can assume that you've run this software several times. What were you doing when you experienced this issue?

It's the example model included in the prebuilt windows package listed in the English documentation here:
https://github.com/w-okada/voice-changer/blob/master/README_en.md

![bild](https://github.com/w-okada/voice-changer/assets/49168045/5f88c1ef-a521-4394-a94f-99b78f20d711)

They're included in the prepackage in \model_dir\rvc\0

![bild](https://github.com/w-okada/voice-changer/assets/49168045/ce2b83b5-7b4e-4f11-8b88-61c8975f6461)

I assumed these were example modules for testing, but maybe not?

**Comment by Cragsand** [comment]
I think I realize where I messed up. I confused two different packages and these models are not trained for this.
Is there any example models I can try?

**Comment by Cragsand** [comment]
I think I realize where I messed up. I confused two different packages. 

The models I used were the samples included from koemake_v01_00_01: https://koemake.com/termsofusenew 
Tsukuyomi and DendenMei. They're from another voice changer project and likely not compatible.


This is the log I get when trying to load them:
```[Voice Changer] Model Load Error! Check your model is valid. 'Voice Changer is not selected.'
[Voice Changer] Voice Changer is not selected.
[2023-06-07 21:06:22] connet sid : 3z1VbgWkafNcxi5kAAAV
[2023-06-07 21:06:22] connet sid : kDGoCTpQbKH9D3yUAAAX
[Voice Changer] RVC initialization:  VoiceChangerParams(model_dir='model_dir', content_vec_500='pretrain/checkpoint_best_legacy_500.pt', co
ntent_vec_500_onnx='pretrain/checkpoint_best_legacy_500.onnx', content_vec_500_onnx_on=0, hubert_base='pretrain/hubert_base.pt', hubert_bas
e_jp='pretrain/rinna_hubert_base_jp.pt', hubert_soft='pretrain/hubert/hubert-soft-0d54a1f4.pt', nsf_hifigan='pretrain/nsf_hifigan/model', r
vc_sample_mode='production')
[Voice Changer] loading sample info error: RVCModelSample.__init__() got an unexpected keyword argument 'icon'
loadModel {'defaultTune': 0, 'defaultIndexRatio': 1, 'defaultProtect': 0.5, 'sampleId': '', 'rvcIndexDownload': True, 'files': {'rvcModel':
 'C:\\Users\\Crag\\AppData\\Local\\Temp\\tmp2iuyge5u\\upload_dir\\0\\Tsukuyomi.pth', 'rvcIndex': 'C:\\Users\\Crag\\AppData\\Local\\Temp\\tm
p2iuyge5u\\upload_dir\\0\\Tsukuyomi.index'}}
[Voice Changer] Official Model(pyTorch) : v1
[Voice Changer] Prepare Model of slot: 0
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer]  exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 25, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 45, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 12, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] Loading index...
Try loading... model_dir\rvc\0\Tsukuyomi.index
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 334, in loadModel
  File "voice_changer\RVC\RVC.py", line 171, in loadModel
  File "voice_changer\RVC\RVC.py", line 244, in prepareModel
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 45, in createPipeline
UnboundLocalError: local variable 'embedder' referenced before assignment

[Voice Changer] Model Load Error! Check your model is valid. local variable 'embedder' referenced before assignment
2023-06-07T19:10:43.310ZE [22724:NonCelloThread] thumbnail_util_win.cc:115:LoadBitmapFromPngResource Can't find PNG resource 0.
2023-06-07T19:10:43.311ZI [22724:NonCelloThread] ctxmenu.cc:213:GenerateContextMenu Received context menu with 0 menu items.
loadModel {'defaultTune': 0, 'defaultIndexRatio': 1, 'defaultProtect': 0.5, 'sampleId': '', 'rvcIndexDownload': True, 'files': {'rvcModel':
 'C:\\Users\\Crag\\AppData\\Local\\Temp\\tmp2iuyge5u\\upload_dir\\0\\DendenMei.pth', 'rvcIndex': 'C:\\Users\\Crag\\AppData\\Local\\Temp\\tm
p2iuyge5u\\upload_dir\\0\\DendenMei.index'}}
[Voice Changer] Official Model(pyTorch) : v1
[Voice Changer] Prepare Model of slot: 0
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer]  exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 25, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 45, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 12, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] Loading index...
Try loading... model_dir\rvc\0\DendenMei.index
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 334, in loadModel
  File "voice_changer\RVC\RVC.py", line 171, in loadModel
  File "voice_changer\RVC\RVC.py", line 244, in prepareModel
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 45, in createPipeline
UnboundLocalError: local variable 'embedder' referenced before assignment

[Voice Changer] Model Load Error! Check your model is valid. local variable 'embedder' referenced before assignment```

**Comment by w-okada** [comment]
There is no compatibility.
So this is natural. 
Issue is resolved?

**Comment by Cragsand** [comment]
> There is no compatibility. So this is natural. Issue is resolved?

Trained my own model following this guide 
https://www.youtube.com/watch?v=-JcvdDErkAU
And this webui repo https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI

Still getting the same issue

![bild](https://github.com/w-okada/voice-changer/assets/49168045/927e82a2-ff9a-4280-8c53-195e5f7c2ec0)


Log:

````N:\Python\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_
legacy_500.pt     --content_vec_500_onnx pretrain/checkpoint_best_legacy_500.onnx     --content_vec_500_onnx_on false
  --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain
/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --model_dir model_dir     --samples sam
ples.json
    Booting PHASE :__main__
    Voice Changerを起動しています。
++    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
VoiceChanger Initialized (GPU_NUM:1, mps_enabled:False)
 [INFO] [DSH]  voice-changer-native-client.exe
 [INFO] [DSH]  Creating WndMsg Listener Window
 [INFO] [DSH]  Get number of capabilities
 [INFO] [DSH]  Get stream caps: 0
 [INFO] [DSH]  Get stream caps: 1
 [INFO] [DSH]  Get stream caps: 2
 [INFO] [DSH]  Get stream caps: 3
 [INFO] [DSH]  Get stream caps: 4
 [INFO] [DSH]  Get stream caps: 5
 [INFO] [DSH]  Get stream caps: 6
 [INFO] [DSH]  Get stream caps: 7
 [INFO] [DSH]  Get stream caps: 8
 [INFO] [DSH]  Get stream caps: 9
 [INFO] [DSH]  Get stream caps: 10
 [INFO] [DSH]  Get stream caps: 11
 [INFO] [DSH]  Get stream caps: 12
 [INFO] [DSH]  Get stream caps: 13
 [INFO] [DSH]  Get stream caps: 14
 [INFO] [DSH]  Get stream caps: 15
 [INFO] [DSH]  Get stream caps: 16
 [INFO] [DSH]  Get stream caps: 17
 [INFO] [DSH]  Get stream caps: 18
 [INFO] [DSH]  Get stream caps: 19
 [INFO] [DSH]  Get stream caps: 20
 [INFO] [DSH]  Get stream caps: 21
 [INFO] [DSH]  Get stream caps: 22
 [INFO] [DSH]  Get stream caps: 23
 [INFO] [DSH]  Get stream caps: 24
 [INFO] [DSH]  Get stream caps: 25
 [INFO] [DSH]  Get stream caps: 26
 [INFO] [DSH]  Get stream caps: 27
 [INFO] [DSH]  Get stream caps: 28
 [INFO] [DSH]  Get stream caps: 29
 [INFO] [DSH]  Get stream caps: 30
 [INFO] [DSH]  Get stream caps: 31
 [INFO] [DSH]  Get stream caps: 32
 [INFO] [DSH]  Destroying object
 [INFO] [DSH]  Destroying WndMsg Listener Window
 [INFO] [DSH]  Destroyed window
 [INFO] [DSH]  Unregistered window class
[2023-06-07 21:57:53] connet sid : rra3tzUbPU2l0Lw0AAAB
[2023-06-07 21:57:53] connet sid : wD4oCwscgaYyw3wZAAAD
2023-06-07 21:57:55 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-06-07 21:57:55 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-06-07 21:57:55 | INFO | faiss.loader | Loading faiss.
2023-06-07 21:57:55 | INFO | faiss.loader | Successfully loaded faiss.
[Voice Changer] RVC initialization:  VoiceChangerParams(model_dir='model_dir', content_vec_500='pretrain/checkpoint_best
_legacy_500.pt', content_vec_500_onnx='pretrain/checkpoint_best_legacy_500.onnx', content_vec_500_onnx_on=0, hubert_base
='pretrain/hubert_base.pt', hubert_base_jp='pretrain/rinna_hubert_base_jp.pt', hubert_soft='pretrain/hubert/hubert-soft-
0d54a1f4.pt', nsf_hifigan='pretrain/nsf_hifigan/model', rvc_sample_mode='production')
[Voice Changer] loading sample info error: RVCModelSample.__init__() got an unexpected keyword argument 'icon'
[Voice Changer] Prepare Model of slot: 0
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer]  exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central dire
ctory
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 25, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 45, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 12, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] Loading index...
Try loading... model_dir\rvc\0\DendenMei.index
local variable 'embedder' referenced before assignment
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 312, in switchModelType
  File "voice_changer\RVC\RVC.py", line 92, in __init__
  File "voice_changer\RVC\RVC.py", line 244, in prepareModel
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 45, in createPipeline
UnboundLocalError: local variable 'embedder' referenced before assignment

Exception ignored in: <function RVC.__del__ at 0x000002178F88D6C0>
Traceback (most recent call last):
  File "voice_changer\RVC\RVC.py", line 401, in __del__
AttributeError: pipeline
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 331, in loadModel
Exceptions.VoiceChangerIsNotSelectedException: 'Voice Changer is not selected.'

[Voice Changer] Model Load Error! Check your model is valid. 'Voice Changer is not selected.'
```

**Comment by w-okada** [comment]
Please read tutorial. you may use wrong file.

**Comment by w-okada** [comment]
https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md

**Comment by Cragsand** [comment]
Deleted the folder **%appdata%\voice-changer-native-client** and seems to work now. Cheers

**Comment by w-okada** [comment]
OK
