### ISSUE TITLE
 Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (48000, 48000) at dimension 1 of input [1, 9370]

### ISSUE THREAD

**Issue by nanowell** [w-okada/voice-changer#302]
### Issue Type

Bug Report

### vc client version number

1.5.3.4d

### OS

Win 10 x64

### GPU

3060 ti

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Voice Changer type

RVC

### Model type

ONNX, RVC V2

### Situation

console log error:  Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (48000, 48000) at dimension 1 of input [1, 9370]
It can't get any mic input even though mic is working perfectly well, I tested it in lots of other programs and daws.
Screenshot: 
![image](https://github.com/w-okada/voice-changer/assets/46109023/0b75e68a-e60d-4944-ac4a-ee959b22f87e)

**Comment by w-okada** [comment]
Wrong padding process runs. Could you try to clear setting.

**Comment by HidekoHaruna** [comment]
> Wrong padding process runs. Could you try to clear setting.

that doesn't work

**Comment by w-okada** [comment]
Okay!! I have reproduced it. I will fix it in the next version. Until then, please use it with a low quality.

**Comment by w-okada** [comment]
I have fixed this issue.
try v.1.5.3.5a.

**Comment by nanowell** [comment]
Thank you, w-okada!

**Comment by nanowell** [comment]
Fixed.

**Comment by AutoJumper** [comment]
Error still occurs for me as of 1.5.3.5, only happens when changing from RVC Quality from low to high.
![image](https://github.com/w-okada/voice-changer/assets/29980251/fdaeb5b9-4524-4c64-9ad5-1de30a8e4288)
